from pathlib import Path

import pytest

from reccy.runtime import assets, value_assets


def _key() -> str:
    return assets.source_fingerprint(
        {'provider': 'example', 'version': '1'},
        {'arguments': {'pitch': 69}},
        None,
        {'sample_rate': 48000, 'dtype': 'float32', 'encoder': 'wav-1'},
    )


def test_deterministic_value_reuses_verified_bytes_without_calling_provider(
    tmp_path: Path,
) -> None:
    store = assets.AssetStore(tmp_path / 'cache', credential_scope='public')
    calls = 0

    def produce() -> bytes:
        nonlocal calls
        calls += 1
        return b'generated bytes'

    for _ in range(2):
        with value_assets.open_deterministic_asset(
            store, _key(), produce, maximum_bytes=100
        ) as (entry, file):
            assert entry.category is assets.AssetCategory.generated
            assert file.read() == b'generated bytes'
    assert calls == 1
    assert len(list((store.root / 'entries').glob('*.json'))) == 1


def test_collected_value_regenerates_only_if_identity_matches(tmp_path: Path) -> None:
    store = assets.AssetStore(tmp_path / 'cache', credential_scope='public')
    with value_assets.open_deterministic_asset(
        store, _key(), lambda: b'first', maximum_bytes=100
    ) as (first, file):
        assert file.read() == b'first'
    assert store.collect([]) == [first.id]
    with value_assets.open_deterministic_asset(
        store, _key(), lambda: b'first', maximum_bytes=100
    ) as (second, file):
        assert file.read() == b'first'
    assert second.id != first.id
    assert store.collect([]) == [second.id]
    with pytest.raises(value_assets.AssetValueConflict, match='changed'):
        with value_assets.open_deterministic_asset(
            store, _key(), lambda: b'other', maximum_bytes=100
        ):
            pass
    with pytest.raises(value_assets.AssetValueConflict, match='invalidated'):
        with value_assets.open_deterministic_asset(
            store, _key(), lambda: b'first', maximum_bytes=100
        ):
            pass
    assert list((store.root / 'entries').glob('*.json')) == []


def test_oversized_value_is_rejected_before_admission(tmp_path: Path) -> None:
    store = assets.AssetStore(tmp_path / 'cache', credential_scope='public')
    with pytest.raises(assets.AssetCacheError, match='maximum_bytes'):
        with value_assets.open_deterministic_asset(
            store, _key(), lambda: b'large', maximum_bytes=4
        ):
            pass
    assert list((store.root / 'entries').glob('*.json')) == []


def test_value_key_cannot_change_media_kind_or_bypass_a_smaller_limit(
    tmp_path: Path,
) -> None:
    store = assets.AssetStore(tmp_path / 'cache', credential_scope='public')
    with value_assets.open_deterministic_asset(
        store,
        _key(),
        lambda: b'image',
        maximum_bytes=100,
        media_kind=assets.MediaKind.image,
    ):
        pass
    with pytest.raises(value_assets.AssetValueConflict, match='media kind'):
        with value_assets.open_deterministic_asset(
            store,
            _key(),
            lambda: b'image',
            maximum_bytes=100,
            media_kind=assets.MediaKind.audio,
        ):
            pass
    with pytest.raises(assets.AssetCacheError, match='maximum_bytes'):
        with value_assets.open_deterministic_asset(
            store,
            _key(),
            lambda: b'image',
            maximum_bytes=4,
            media_kind=assets.MediaKind.image,
        ):
            pass
