"""Compatibility imports for :mod:`reccy.protocol.ipc`."""

from .protocol.ipc import (
    Connection,
    Error,
    Hello,
    ProtocolClient,
    ProtocolListener,
    Reply,
    ServerBackend,
    Shutdown,
    UnixSocketConnection,
    UnixSocketServerBackend,
    WindowsPipeConnection,
    WindowsPipeServerBackend,
    client_connection,
    connect_windows_pipe,
    connection,
    message_json,
    parse_message,
    remove_stale_socket,
    server_backend,
)

__all__ = [
    'Connection',
    'Error',
    'Hello',
    'ProtocolClient',
    'ProtocolListener',
    'Reply',
    'ServerBackend',
    'Shutdown',
    'UnixSocketConnection',
    'UnixSocketServerBackend',
    'WindowsPipeConnection',
    'WindowsPipeServerBackend',
    'client_connection',
    'connection',
    'connect_windows_pipe',
    'message_json',
    'parse_message',
    'remove_stale_socket',
    'server_backend',
]
